CREATE SEQUENCE TB_USUARIO_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE
;

CREATE TABLE TB_USUARIO (
    USUARIO_ID INTEGER DEFAULT TB_USUARIO_SEQ.NEXTVAL NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    SENHA VARCHAR2(15) NOT NULL
    ROLE VARCHAR(50) DEFAULT "USER"
);

